version: '3'
services:
  apollo-gateway:
    container_name: apollo-gateway
    build: ./gateway
    env_file:
      - graph-api.env
    ports:
      - "4001:4001"

  #db:
  #  image: postgres:12
  #  container_name: demo_postgres
  #  env_file: .env.local
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres:/var/lib/postgresql/data

#volumes:
# postgres:
