service: supergraph-serverless

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  products:
    handler: src/subgraphs/products/index.handler
    events:
      - http:
          path: products
          method: ANY
          cors: true
  users:
    handler: src/subgraphs/users/index.handler
    events:
      - http:
          path: users
          method: ANY
          cors: true

custom:
  serverless-offline:
    noPrependStageInUrl: true
    useChildProcesses: true
    host: 0.0.0.0
    httpPort: 4000
